language: ruby

import:
  - travis-ci/build-configs:db-setup.yml

rvm: 2.3.6

script: "bundle exec rake knapsack:rspec"

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - CI_NODE_TOTAL=3

  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2

services:
  - redis-server

install:
  - 'gem update --system'
  - 'gem install bundler -v 1.16.1'
  - 'bundle update fog-core'