language: ruby

sudo: false

rvm: 2.3.6

script: "bundle exec rake knapsack:rspec"
env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - CI_NODE_TOTAL=3

  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2

addons:
  postgresql: 9.3

services:
  - redis-server

before_install:
  - travis_retry gem install bundler -v '<2' # Ruby 2.2 depend on bundler 1.x.

install:
  - bundler -v
  - travis_retry bundle install

before_script:
  - 'RAILS_ENV=test bundle exec rake db:create --trace'